{
 "title": "pfSense",
 "tags": [
  "m0n0wall",
  "FreeBSD"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "query": "pfsense.*" },
   { "name": "interface", "query": "pfsense.$hostname.net.*" },
   { "name": "ping", "query": "pfsense.$hostname.ping.*" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMinima(pfsense.$hostname.cpu.cpu-total.*), 4)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(pfsense.$hostname.system.load*, 3)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(pfsense.$hostname.mem.wired, 3)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.mem.active, 3)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.mem.buffered, 3)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.mem.cached, 3)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.mem.free, 3)"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(pfsense.$hostname.swap.used, 3)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.swap.free, 3)"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "md0 usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(pfsense.$hostname.disk.ufsid-57fbabd3938f945a.*.*.*.used, 7)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.disk.ufsid-57fbabd3938f945a.*.*.*.free, 7)"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.diskio.md0.reads, 60)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.diskio.md0.writes, 60)), 4)"
    },
    {
     "target": "aliasByNode(derivative(pfsense.$hostname.diskio.md0.io_time), 4)"
    }
   ]
  },
  { "title": "Network Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "repeat": "interface",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_sent, 10)), 4)"
    }
   ]
  },
  { "title": "Network PPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "repeat": "interface",
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_sent, 10)), 4)"
    }
   ]
  },
  { "title": "Packet Filter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "State Table",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(pfsense.$hostname.pf.entries, 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.inserts), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.removals), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.searches), 3)"
    }
   ]
  },
  {
   "title": "Counters",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.match), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.bad-offset), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.fragment), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.short), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.normalize), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.memory), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.bad-timestamp), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.congestion), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.ip-option), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.proto-cksum), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.state-mismatch), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.state-insert), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.state-limit), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.src-limit), 3)"
    },
    {
     "target": "aliasByNode(nonNegativeDerivative(pfsense.$hostname.pf.synproxy), 3)"
    }
   ]
  },
  { "title": "Ping Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "$ping",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 68 },
   "repeat": "ping",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(pfsense.$hostname.ping.$ping.minimum_response_ms, 'min')"
    },
    {
     "target": "alias(pfsense.$hostname.ping.$ping.average_response_ms, 'avg')"
    },
    {
     "target": "alias(pfsense.$hostname.ping.$ping.maximum_response_ms, 'max')"
    }
   ]
  }
 ]
}