{
 "title": "VMware Cluster Multi ESX LiteStats",
 "tags": [
  "CPU",
  "RAM",
  "uptime"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "vcenter", "query": "vmw.*" },
   { "name": "datacentre", "query": "vmw.$vcenter.*" },
   { "name": "cluster", "query": "vmw.$vcenter.$datacentre.*" },
   {
    "name": "esx",
    "query": "vmw.$vcenter.$datacentre.$cluster.esx.*"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "cpu" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vmw.$vcenter.$datacentre.$cluster.esx.$esx.fatstats.overallCpuUtilization, 5)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "hertz", "label": "cpu" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(vmw.$vcenter.$datacentre.$cluster.esx.$esx.quickstats.overallCpuUsage, 1000000), 5)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RAM Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent", "label": "cpu" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vmw.$vcenter.$datacentre.$cluster.esx.$esx.fatstats.overallmemUtilization, 5)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes", "label": "cpu" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scale(vmw.$vcenter.$datacentre.$cluster.esx.$esx.quickstats.overallMemoryUsage, 1048576), 5)"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vmw.$vcenter.$datacentre.$cluster.esx.$esx.quickstats.Uptime, 5)"
    }
   ]
  }
 ]
}