{
 "title": "VMware All Cluster SuperStats",
 "tags": [
  "CPU",
  "RAM",
  "HDD",
  "VM",
  "vmotion",
  "vmnic",
  "IORM",
  "vmhba"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "vcenter", "query": "vmw.*" },
   { "name": "datacentre", "query": "vmw.$vcenter.*" },
   { "name": "cluster", "query": "vmw.$vcenter.$datacentre.*" }
  ]
 },
 "panels": [
  { "title": "$cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cpu/ram usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.cpu.usage), #A), 'cpu.usage')",
     "targetFull": "alias(asPercent(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.cpu.usage), sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.cpu.effective)), 'cpu.usage')"
    },
    {
     "target": "alias(diffSeries(asPercent(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.usage), #B), #C), 'mem.usage')",
     "targetFull": "alias(diffSeries(asPercent(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.usage), sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.effective)), alias(asPercent(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.cpu.usage), sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.cpu.effective)), 'cpu.usage')), 'mem.usage')"
    },
    {
     "target": "alias(asPercent(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.vRAM), #B), 'mem.allocated')",
     "targetFull": "alias(asPercent(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.vRAM), sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.effective)), 'mem.allocated')"
    },
    {
     "target": "alias(scale(averageSeries(vmw.$vcenter.$datacentre.$cluster.superstats.cpu.latency), 0.01), 'cpu.latency')"
    }
   ]
  },
  {
   "title": "memory quickstats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.private), 'private')"
    },
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.shared), 'shared')"
    },
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.ballooned), 'ballooned')"
    },
    {
     "target": "alias(sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.compressed, 0.0009765625)), 'zipped')"
    },
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.swapped), 'swapped')"
    },
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.guest), 'active')"
    },
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.consumedOverhead), 'overhead')"
    }
   ]
  },
  {
   "title": "shared datastores utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(diffSeries(sumSeries(vmw.$vcenter.$datacentre.$cluster.superstats.datastore.capacity), #A), 'used')",
     "targetFull": "alias(diffSeries(sumSeries(vmw.$vcenter.$datacentre.$cluster.superstats.datastore.capacity), sumSeries(vmw.$vcenter.$datacentre.$cluster.superstats.datastore.freeSpace)), 'used')"
    },
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.superstats.datastore.uncommitted), 'uncommitted')"
    },
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.superstats.datastore.capacity), 'capacity')"
    },
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.superstats.datastore.count), 'datastores')"
    }
   ]
  },
  {
   "title": "vmnic traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.superstats.net.bytesRx, 1024)), 6)"
    },
    {
     "target": "aliasByNode(sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.superstats.net.bytesTx, 1024)), 6)"
    }
   ]
  },
  {
   "title": "VM count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.runtime.vm.on), 'vm.on')"
    },
    {
     "target": "alias(diffSeries(sumSeries(vmw.$vcenter.$datacentre.$cluster.runtime.vm.total), #A), 'vm.registered')",
     "targetFull": "alias(diffSeries(sumSeries(vmw.$vcenter.$datacentre.$cluster.runtime.vm.total), alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.runtime.vm.on), 'vm.on')), 'vm.registered')"
    },
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.superstats.esx.count), 'hosts')"
    },
    {
     "target": "alias(sumSeries(removeEmptySeries(removeBelowValue(vmw.$vcenter.$datacentre.$cluster.runtime.vm.dead, 1))), 'vm.zombie')"
    }
   ]
  },
  {
   "title": "vmhba traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.superstats.hba.bytesRead, 1024)), 6)"
    },
    {
     "target": "aliasByNode(sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.superstats.hba.bytesWrite, 1024)), 6)"
    }
   ]
  },
  {
   "title": "RAM utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.guest), 'guest')"
    },
    {
     "target": "alias(diffSeries(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.private), #C), 'private')",
     "targetFull": "alias(diffSeries(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.private), alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.guest), 'guest')), 'private')"
    },
    {
     "target": "alias(diffSeries(#B, #D), 'effective')",
     "targetFull": "alias(diffSeries(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.effective), alias(diffSeries(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.private), alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.guest), 'guest')), 'private')), 'effective')"
    },
    {
     "target": "alias(diffSeries(#A, #B), 'total')",
     "targetFull": "alias(diffSeries(sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.total, 9.5367431640625e-7)), sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.mem.effective)), 'total')"
    },
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.quickstats.vRAM), 'alocated')"
    }
   ]
  },
  {
   "title": "CPU utilization/demand",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.quickstats.cpu.demand, 1000000)), 'demand')"
    },
    {
     "target": "alias(sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.quickstats.cpu.usage, 1000000)), 'usage')"
    },
    {
     "target": "alias(diffSeries(#B, #D), 'effective')",
     "targetFull": "alias(diffSeries(sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.quickstats.cpu.effective, 1000000)), alias(sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.quickstats.cpu.usage, 1000000)), 'usage')), 'effective')"
    },
    {
     "target": "alias(diffSeries(#A, #B), 'total')",
     "targetFull": "alias(diffSeries(sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.quickstats.cpu.total, 1000000)), sumSeries(scale(vmw.$vcenter.$datacentre.$cluster.quickstats.cpu.effective, 1000000))), 'total')"
    }
   ]
  },
  {
   "title": "vCPU per pCPU ratio",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(divideSeries(#B, #A), 'vCPU/pCPU')"
    }
   ]
  },
  {
   "title": "power usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "target": "groupByNode(vmw.$vcenter.$datacentre.$cluster.superstats.power, 3, 'sum')"
    }
   ]
  },
  {
   "title": "vMotion count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(nonNegativeDerivative(vmw.$vcenter.$datacentre.$cluster.quickstats.numVmotions)), 'vmotion')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(vmw.$vcenter.$datacentre.$cluster.quickstats.numSVMotions)), 'svmotion')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(vmw.$vcenter.$datacentre.$cluster.quickstats.numXVMotions)), 'xvmotion')"
    }
   ]
  },
  {
   "title": "MultipathState Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "sortBy(groupByNode(removeEmptySeries(vmw.$vcenter.$datacentre.$cluster.superstats.PathState.*), 6, 'total'), 'last', false)"
    }
   ]
  },
  { "title": "IOPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Normalized Datastores Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(vmw.$vcenter.$datacentre.$cluster.superstats.datastore.mid_latency), 'Avg')"
    },
    {
     "target": "alias(maxSeries(vmw.$vcenter.$datacentre.$cluster.superstats.datastore.max_latency), 'Max')"
    }
   ]
  },
  {
   "title": "Aggregated Datastores IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(vmw.$vcenter.$datacentre.$cluster.superstats.datastore.iops), 'IOPS')"
    }
   ]
  }
 ]
}