{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(collectd.sexigraf.aggregation-cpu-average.{cpu-wait,cpu-nice,cpu-interrupt,cpu-nice,cpu-softirq,cpu-steal,cpu-system,cpu-user})"
    },
    {
     "target": "aliasByMetric(collectd.sexigraf.aggregation-cpu-average.cpu-idle)"
    }
   ]
  },
  {
   "title": "mem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.sexigraf.memory.memory-used, 3)"
    },
    {
     "target": "aliasByNode(collectd.sexigraf.memory.memory-cached, 3)"
    },
    {
     "target": "aliasByNode(collectd.sexigraf.memory.memory-buffered, 3)"
    },
    {
     "target": "aliasByNode(collectd.sexigraf.memory.memory-free, 3)"
    }
   ]
  },
  {
   "title": "load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.sexigraf.load.load.*, 4)"
    }
   ]
  },
  {
   "title": "df-root",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.sexigraf.df-root.df_complex-reserved, 3)"
    },
    {
     "target": "aliasByNode(collectd.sexigraf.df-root.df_complex-used, 3)"
    },
    {
     "target": "aliasByNode(collectd.sexigraf.df-root.df_complex-free, 3)"
    }
   ]
  },
  {
   "title": "df-wfs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.sexigraf.df-mnt-wfs.df_complex-reserved, 3)"
    },
    {
     "target": "aliasByNode(collectd.sexigraf.df-mnt-wfs.df_complex-used, 3)"
    },
    {
     "target": "aliasByNode(collectd.sexigraf.df-mnt-wfs.df_complex-free, 3)"
    }
   ]
  },
  {
   "title": "if",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(collectd.sexigraf.interface-eth0.if_octets.*, 4)"
    }
   ]
  }
 ]
}