{
 "title": "VMware All Versions",
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "vcenter", "query": "vi.*" },
   { "name": "datacentre", "query": "vi.$vcenter.vi.version.esx.*" },
   {
    "name": "cluster",
    "query": "vi.$vcenter.vi.version.esx.$datacentre.*"
   }
  ]
 },
 "panels": [
  { "title": "VPX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vCenter Build",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByTotal(removeEmptySeries(groupByNode(vi.$vcenter.vi.version.vpx.product.*, 6, 'sum')))"
    }
   ]
  },
  { "title": "ESX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "ESX Build",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByTotal(removeEmptySeries(groupByNode(vi.$vcenter.vi.version.esx.$datacentre.$cluster.build.*, 8, 'sum')))"
    }
   ]
  },
  {
   "title": "ESX Hardware",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByTotal(removeEmptySeries(groupByNode(vi.$vcenter.vi.version.esx.$datacentre.$cluster.hardware.*, 8, 'sum')))"
    }
   ]
  },
  {
   "title": "ESX CPU",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByTotal(removeEmptySeries(groupByNode(vi.$vcenter.vi.version.esx.$datacentre.$cluster.cpu.*, 8, 'sum')))"
    }
   ]
  },
  { "title": "VM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "VM Guest",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByTotal(removeEmptySeries(groupByNode(vi.$vcenter.vi.version.vm.$datacentre.$cluster.guest.*, 8, 'sum')))"
    }
   ]
  },
  {
   "title": "VM vHW",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByTotal(removeEmptySeries(groupByNode(vi.$vcenter.vi.version.vm.$datacentre.$cluster.vhw.*, 8, 'sum')))"
    }
   ]
  },
  {
   "title": "VM VMware Tools",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "sortByTotal(removeEmptySeries(groupByNode(vi.$vcenter.vi.version.vm.$datacentre.$cluster.vmtools.*, 8, 'sum')))"
    }
   ]
  }
 ]
}