{
 "title": "VMware Evo Version",
 "tags": [ "VI" ],
 "time": { "from": "now-1d", "to": "now" },
 "templating": {
  "list": [
   { "name": "vcenter", "query": "vi.*" },
   { "name": "datacentre", "query": "vi.$vcenter.vi.version.esx.*" },
   {
    "name": "cluster",
    "query": "vi.$vcenter.vi.version.esx.$datacentre.*"
   },
   {
    "name": "vmtools",
    "query": "vi.$vcenter.vi.version.vm.$datacentre.$cluster.vmtools.*"
   },
   {
    "name": "guestid",
    "query": "vi.$vcenter.vi.version.vm.$datacentre.$cluster.guest.*"
   },
   {
    "name": "vhw",
    "query": "vi.$vcenter.vi.version.vm.$datacentre.$cluster.vhw.*"
   },
   {
    "name": "build",
    "query": "vi.$vcenter.vi.version.esx.$datacentre.$cluster.build.*"
   }
  ]
 },
 "panels": [
  {
   "title": "VMTools version",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "groupByNode(vi.$vcenter.vi.version.vm.$datacentre.$cluster.vmtools.$vmtools, 8, 'sum')"
    }
   ]
  },
  {
   "title": "GuestId version",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "target": "groupByNode(vi.$vcenter.vi.version.vm.$datacentre.$cluster.guest.$guestid, 8, 'sum')"
    }
   ]
  },
  {
   "title": "vHardware version",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "groupByNode(vi.$vcenter.vi.version.vm.$datacentre.$cluster.vhw.$vhw, 8, 'sum')"
    }
   ]
  },
  {
   "title": "ESX version",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "groupByNode(removeEmptySeries(vi.$vcenter.vi.version.esx.$datacentre.$cluster.build.$build), 8, 'sum')"
    }
   ]
  }
 ]
}