{
 "title": "VMware vCenter Resource Counters",
 "tags": [ "VI" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "vCenter", "query": "vi.*" }
  ]
 },
 "panels": [
  {
   "title": "system cpu usage",
   "type": "graph",
   "description": "Total system CPU used on the system where vCenter Server in running",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vi.$vCenter.vi.vcres.systemcpuusage, 1)"
    }
   ]
  },
  {
   "title": "physical mem usage",
   "type": "graph",
   "description": "Physical memory used by vCenter",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vi.$vCenter.vi.vcres.physicalmemusage, 1)"
    }
   ]
  },
  {
   "title": "virtual mem usage",
   "type": "graph",
   "description": "Virtual memory used by vCenter Server",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vi.$vCenter.vi.vcres.virtualmemusage, 1)"
    }
   ]
  }
 ]
}