{
 "title": "pfSense",
 "tags": [
  "pf",
  "linux"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "query": "pfsense.*" },
   { "name": "interface", "query": "pfsense.$hostname.net.*" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByMinima(pfsense.$hostname.cpu.cpu-total.*), 4)"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(pfsense.$hostname.system.load*, 3)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(pfsense.$hostname.mem.wired, 3)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.mem.active, 3)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.mem.buffered, 3)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.mem.cached, 3)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.mem.free, 3)"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(pfsense.$hostname.swap.used, 3)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.swap.free, 3)"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "md0 usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(pfsense.$hostname.disk.ufsid-57fbabd3938f945a.*.*.*.used, 7)"
    },
    {
     "target": "aliasByNode(pfsense.$hostname.disk.ufsid-57fbabd3938f945a.*.*.*.free, 7)"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.diskio.md0.reads, 60)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.diskio.md0.writes, 60)), 4)"
    },
    {
     "target": "aliasByNode(derivative(pfsense.$hostname.diskio.md0.io_time), 4)"
    }
   ]
  },
  { "title": "Network Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "repeat": "interface",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.bytes_sent, 10)), 4)"
    }
   ]
  },
  { "title": "Network PPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "repeat": "interface",
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_sent, 10)), 4)"
    }
   ]
  },
  {
   "title": "$interface",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_recv, 10)), 4)"
    },
    {
     "target": "aliasByNode(derivative(scaleToSeconds(pfsense.$hostname.net.$interface.packets_sent, 10)), 4)"
    }
   ]
  }
 ]
}