{
 "title": "VMware vSAN Resync & Health",
 "tags": [ "vSAN" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "vcenter", "query": "vsan.*" },
   { "name": "datacentre", "query": "vsan.$vcenter.*" },
   { "name": "cluster", "query": "vsan.$vcenter.$datacentre.*" }
  ]
 },
 "panels": [
  {
   "title": "Bytes To Sync",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vsan.$vcenter.$datacentre.$cluster.vsan.SyncingVsanObjects.bytesToSync.*, 7)"
    },
    {
     "target": "aliasByNode(vsan.$vcenter.$datacentre.$cluster.vsan.SyncingVsanObjects.totalBytesToSync, 6)"
    }
   ]
  },
  {
   "title": "Total Objects/Components To Sync",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vsan.$vcenter.$datacentre.$cluster.vsan.SyncingVsanObjects.totalComponentsToSync, 6)"
    },
    {
     "target": "aliasByNode(vsan.$vcenter.$datacentre.$cluster.vsan.SyncingVsanObjects.totalObjectsToSync, 6)"
    }
   ]
  },
  {
   "title": "Total Recovery ETA",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "target": "aliasByNode(vsan.$vcenter.$datacentre.$cluster.vsan.SyncingVsanObjects.totalRecoveryETA, 6)"
    }
   ]
  },
  {
   "title": "Object Health Detail",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(currentAbove(vsan.$vcenter.$datacentre.$cluster.vsan.ObjectHealthDetail.*, 0), 6))"
    }
   ]
  },
  {
   "title": "HealthScore",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "sortByMaxima(aliasByNode(vsan.$vcenter.$datacentre.$cluster.vsan.healthSummary.healthScore, 6))"
    }
   ]
  }
 ]
}