{
 "title": "VMware vSAN Monitor TCP",
 "tags": [
  "vSAN",
  "TCPIP"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "vcenter", "query": "vsan.*" },
   { "name": "datacentre", "query": "vsan.$vcenter.*" },
   { "name": "cluster", "query": "vsan.$vcenter.$datacentre.*" },
   {
    "name": "hostname",
    "label": "esx",
    "query": "vsan.$vcenter.$datacentre.$cluster.esx.*"
   }
  ]
 },
 "panels": [
  { "title": "$hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.rcvpack), 1), 'Inbound')"
    },
    {
     "target": "alias(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.sndpack), 1), 'Outbound')"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.rcvbyte), 1), 'Inbound')"
    },
    {
     "target": "alias(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.sndbyte), 1), 'Outbound')"
    }
   ]
  },
  {
   "title": "Drops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.*drop*), 1), 9)"
    }
   ]
  },
  {
   "title": "SACK/DUP/OOO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.sack_rexmits), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.sack_recovery_episode), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.sack_sboverflow), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.rcvdupack), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.rcvduppack), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.rcvpartduppack), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.rcvacktoomuch), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.rcvoopack), 1), 9)"
    }
   ]
  },
  {
   "title": "Bad",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.*bad*), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.snd_zerowin), 1), 9)"
    }
   ]
  },
  {
   "title": "SynCache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.rcvpackafterwin), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.sc_reset), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.sc_bucketoverflow), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.sc_cacheoverflow), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.sc_unreach), 1), 9)"
    },
    {
     "target": "aliasByNode(scaleToSeconds(nonNegativeDerivative(vsan.$vcenter.$datacentre.$cluster.esx.$hostname.vsan.tcpip.stats.sc_stale), 1), 9)"
    }
   ]
  }
 ]
}