{
 "title": "VMware Multi vSAN Monitor Network",
 "tags": [
  "vSAN",
  "TCPIP"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "vcenter", "query": "vsan.*" },
   { "name": "datacentre", "query": "vsan.$vcenter.*" },
   { "name": "cluster", "query": "vsan.$vcenter.$datacentre.*" }
  ]
 },
 "panels": [
  { "title": "$cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "cluster" },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(vsan.$vcenter.$datacentre.$cluster.esx.*.vsan.net.rxPackets), 'Inbound')"
    },
    {
     "target": "alias(sumSeries(vsan.$vcenter.$datacentre.$cluster.esx.*.vsan.net.txPackets), 'Outbound')"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(vsan.$vcenter.$datacentre.$cluster.esx.*.vsan.net.rxThroughput), 'Inbound')"
    },
    {
     "target": "alias(sumSeries(vsan.$vcenter.$datacentre.$cluster.esx.*.vsan.net.txThroughput), 'Outbound')"
    }
   ]
  },
  {
   "title": "TCP Rx Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeries(vsan.$vcenter.$datacentre.$cluster.esx.*.vsan.net.tcpRxErrRate), 8)"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeries(vsan.$vcenter.$datacentre.$cluster.esx.*.vsan.net.rxPacketsLossRate), 8)"
    },
    {
     "target": "aliasByNode(averageSeries(vsan.$vcenter.$datacentre.$cluster.esx.*.vsan.net.txPacketsLossRate), 8)"
    }
   ]
  },
  {
   "title": "TCP Tx Rexmit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeries(vsan.$vcenter.$datacentre.$cluster.esx.*.vsan.net.tcpTxRexmitRate), 8)"
    }
   ]
  },
  {
   "title": "Drops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeries(vsan.$vcenter.$datacentre.$cluster.esx.*.vsan.net.portRxDropsRate), 8)"
    },
    {
     "target": "aliasByNode(averageSeries(vsan.$vcenter.$datacentre.$cluster.esx.*.vsan.net.portTxDropsRate), 8)"
    }
   ]
  }
 ]
}